language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - black ./
  - flake8 ./
  - coverage run --source=swe1,helloworld,polls manage.py test

after_success:
  coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: 'us-west-2'
  app: "django-polls-app"
  env: "poll-app"
  bucket_name: "elasticbeanstalk-us-west-2-476244886696"
  on:
    all_branches: true